version: '3'
networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.30.0.0/24

services:
  scala-common-nlp-japanese-web:
    image: toposoid/scala-common-nlp-japanese-web:0.1-SNAPSHOT
    environment:
      - PRIVATE_IP_ADDRESS=localhost
      - PLAY_HTTP_PORT=9006
    networks:
      app_net:
        ipv4_address: 172.30.0.2
    ports:
      - 9006:9006



